# config/environments/production.yaml
deployment:
  platform: "agent_engine"
  project_id: "my-gcp-project"
  region: "us-central1"
  min_replicas: 3
  max_replicas: 20

memory:
  backend: "weaviate"
  weaviate_url: "https://sre_assistant.weaviate.network"
  weaviate_api_key: "${WEAVIATE_API_KEY}" # 從環境變數讀取
