# sre_assistant/config/environments/staging.yaml
auth:
  provider: "oauth2"
  oauth_client_id: "${OAUTH_CLIENT_ID}"
  oauth_client_secret: "${OAUTH_CLIENT_SECRET}"
  oauth_redirect_uri: "https://staging.sre-assistant.com/callback"
  oauth_scopes:
    - "email"
    - "profile"
    - "sre.operator"
  enable_rbac: true
  enable_rate_limiting: true
  max_requests_per_minute: 60
