
# -*- coding: utf-8 -*-
# ADK Web Dev UI 設定檔（可選）
web:
  dev_ui:
    enabled: true
    host: "0.0.0.0"
    port: 8080
  features:
    conversation_panel: true
    tools_explorer: true
    session_manager: true
    event_stream_viewer: true
    state_inspector: true
    metrics_dashboard: true
  auth:
    enabled: false

agent:
  name: "SRE Assistant"
  description: "Intelligent SRE operations assistant powered by ADK"
  version: "2.0.0"

sessions:
  storage: "memory"   # 或 database（對應我們的 DatabaseSessionService）
  ttl: 3600
