version: "3.9"
services:
  db: { image: postgres:16, environment: { POSTGRES_PASSWORD: postgres }, ports: [ "5432:5432" ] }
  collector:
    image: otel/opentelemetry-collector:0.98.0
    volumes: [ "../deploy/collector/alloy-otel-config.yaml:/etc/otelcol/config.yaml" ]
    command: ["--config=/etc/otelcol/config.yaml"]
    ports: [ "4317:4317", "9464:9464" ]
  prometheus: { image: prom/prometheus:v2.54.1, ports: [ "9090:9090" ] }
  grafana: { image: grafana/grafana:11.1.0, ports: [ "3000:3000" ] }
  app:
    build: ..
    environment: { OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4317 }
    ports: [ "8000:8000" ]
    depends_on: [collector, db]
