# config/environments/development.yaml
deployment:
  platform: "local"
  debug: true

memory:
  backend: "postgresql"
  postgres_connection_string: "postgresql://localhost/sre_dev"

auth:
  provider: "local"
  enable_rbac: false
  enable_rate_limiting: false
