# config/environments/development.yaml
deployment:
  platform: "local"
  debug: true

memory:
  backend: "postgresql"
  postgres_connection_string: "postgresql+psycopg2://postgres:postgres@localhost:5432/sre_assistant"

session_backend: "postgresql"

auth:
  provider: "none"
  enable_rbac: false
  enable_rate_limiting: false
