# src/sre_assistant/config/base.yaml - 基礎配置
deployment:
  platform: "local"
  host: "0.0.0.0"
  port: 8080

memory:
  backend: "memory"
  embedding_model: "textembedding-gecko@003"
  embedding_dimension: 768

llm_model: "gemini-2.0-flash"
temperature: 0.2

auth:
  provider: "local" # 默認本地開發
  enable_rbac: false
  enable_rate_limiting: false
  enable_audit_logging: true
